SELECT CLIENT_ID, ORDER_ID, ORDER_STATUS FROM `ORDER` WHERE CLIENT_ID IN (1,3,5);

SELECT * FROM EMPLOYEE WHERE pensja BETWEEN 5000 AND 7000;

SELECT * FROM `ORDER` WHERE MONTH(ORDER_DATE) BETWEEN 6 AND 7;

SELECT * FROM CLIENT WHERE TAX_IDENTIFIER IS NOT NULL ORDER BY SHORT_NAME ASC;

SELECT * FROM EMPLOYEE ORDER BY BIRTH_DATE DESC LIMIT 5;

SELECT DISTINCT FIRST_NAME FROM EMPLOYEE;

SELECT CONCAT(FIRST_NAME, ' - ', LAST_NAME) FROM EMPLOYEE WHERE LAST_NAME LIKE 'Ko%';

SELECT LAST_NAME, pensja, DATE_OF_EMPLOYMENT FROM EMPLOYEE WHERE YEAR(DATE_OF_EMPLOYMENT) BETWEEN 2010 AND 2014;

SELECT pensja, 0.75*pensja AS pensja_netto, 0.25*pensja AS kwota_podatku FROM EMPLOYEE;

SELECT SHORT_NAME FROM CLIENT WHERE FULL_NAME LIKE 'K%' OR FULL_NAME LIKE '%ski' ORDER BY SHORT_NAME DESC;

-- 3 (6)

SELECT AVG(pensja) FROM EMPLOYEE;

SELECT AVG(pensja), COUNT(JOB_POSITION_ID), JOB_POSITION_ID FROM EMPLOYEE GROUP BY JOB_POSITION_ID;

SELECT AVG(DATEDIFF(CURDATE(), BIRTH_DATE)) / 365.25 FROM EMPLOYEE GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, SUM(pensja) AS pensja_departamentu FROM EMPLOYEE GROUP BY DEPARTMENT_ID ORDER BY pensja_departamentu DESC;

SELECT JOB_POSITION_ID, AVG(pensja) AS srednia_pensja
FROM EMPLOYEE
GROUP BY JOB_POSITION_ID
HAVING COUNT(EMPLOYEE_NAME) >= 3 AND srednia_pensja > 3000;

SELECT DEPARTMENT_ID, COUNT(DISTINCT pensja) AS unikalne_pensje
FROM EMPLOYEE
GROUP BY DEPARTMENT_ID
HAVING COUNT(EMPLOYEE_NAME) > 2
ORDER BY unikalne_pensje;

SELECT DEPARTMENT_NAME, COUNT(e.EMPLOYEE_NAME) FROM DEPARTMENT d
JOIN EMPLOYEE e ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

SELECT DEPARTMENT_NAME, GROUP_CONCAT(CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) SEPARATOR ', ') FROM DEPARTMENT d
JOIN EMPLOYEE e ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

SELECT LAST_NAME, POSITION_NAME FROM EMPLOYEE NATURAL JOIN JOB_POSITION WHERE YEAR(BIRTH_DATE) BETWEEN 1990 AND 1999;

SELECT FIRST_NAME, LAST_NAME, BIRTH_DATE, POSITION_NAME FROM EMPLOYEE
INNER JOIN JOB_POSITION
WHERE POSITION_NAME = 'Magazynier'
ORDER BY BIRTH_DATE ASC LIMIT 5;

SELECT c1.SHORT_NAME, c2.SHORT_NAME, c1.CLIENT_ID, c2.CLIENT_ID FROM CLIENT c1
INNER JOIN CLIENT c2 ON c1.CLIENT_ID + 5 = c2.CLIENT_ID;

SELECT JOB_POSITION_ID, AVG(pensja) FROM EMPLOYEE e
JOIN DEPARTMENT d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
WHERE d.DEPARTMENT_NAME NOT LIKE 'IT' AND d.DEPARTMENT_NAME NOT LIKE 'HR'
GROUP BY JOB_POSITION_ID
HAVING COUNT(pensja) > 3;

WITH oldest_and_youngest AS (
    SELECT
        FIRST_NAME, LAST_NAME, BIRTH_DATE, JOB_POSITION_ID, DEPARTMENT_ID,
        ROW_NUMBER() OVER(PARTITION BY JOB_POSITION_ID ORDER BY BIRTH_DATE ASC) AS youngest_rank,
        ROW_NUMBER() OVER(PARTITION BY JOB_POSITION_ID ORDER BY BIRTH_DATE DESC) AS oldest_rank
    FROM EMPLOYEE
)
SELECT jp.POSITION_NAME,
       oldest_and_youngest.FIRST_NAME,
       oldest_and_youngest.LAST_NAME,
       oldest_and_youngest.BIRTH_DATE,
       d.DEPARTMENT_NAME,
       CASE
           WHEN youngest_rank = 1 THEN 'Youngest'
           WHEN oldest_rank = 1 THEN 'Oldest'
       END AS STATUS
FROM oldest_and_youngest
JOIN DEPARTMENT d ON d.DEPARTMENT_ID = oldest_and_youngest.DEPARTMENT_ID
JOIN JOB_POSITION jp ON jp.JOB_POSITION_ID = oldest_and_youngest.JOB_POSITION_ID
WHERE youngest_rank = 1 OR oldest_rank = 1;

-- 7

SELECT * FROM CLIENT WHERE CLIENT_ID NOT IN (SELECT CLIENT_ID FROM `ORDER`);
SELECT * FROM CLIENT c LEFT JOIN `ORDER` ON `ORDER`.CLIENT_ID = c.CLIENT_ID WHERE `ORDER`.ORDER_ID IS NULL;

SELECT uom.UNIT_NAME FROM INVENTORY i RIGHT JOIN UNIT_OF_MEASUREMENT uom ON uom.UNIT_ID = i.UNIT_ID WHERE i.UNIT_ID IS NULL;

SELECT p.PRODUCT_NAME, AVG(op.AMOUNT * (op.SELL_PRICE - p.PURCHASE_PRICE)) AS avg_buy_sell_diff
FROM PRODUCT p
JOIN ORDER_POSITION op ON op.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY avg_buy_sell_diff DESC;

SELECT DISTINCT d.DEPARTMENT_NAME FROM EMPLOYEE e
JOIN `ORDER` o ON e.EMPLOYEE_NAME = o.EMPLOYEE_ID
JOIN DEPARTMENT d on d.DEPARTMENT_ID = e.DEPARTMENT_ID;

SELECT d.DEPARTMENT_NAME, os.STATUS_NAME, SUM(op.AMOUNT * op.SELL_PRICE)
FROM DEPARTMENT d
JOIN EMPLOYEE e on e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN `ORDER` o ON o.EMPLOYEE_ID = e.EMPLOYEE_NAME
JOIN ORDER_POSITION op ON op.ORDER_ID = o.ORDER_ID
JOIN ORDER_STATUS os ON os.STATUS_ID = o.ORDER_STATUS
GROUP BY d.DEPARTMENT_NAME, os.STATUS_NAME;

SELECT CONCAT(p.PRODUCT_NAME, ' (', p.DESCRIPTION, ')') FROM PRODUCT p;

SELECT CONCAT_WS(', ', p.PRODUCT_ID, p.CATEGORY_ID, p.PRODUCT_NAME, p.PURCHASE_PRICE, p.DESCRIPTION) FROM PRODUCT p;

SELECT d.DEPARTMENT_NAME, GROUP_CONCAT(CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) SEPARATOR ', ') FROM DEPARTMENT d
JOIN EMPLOYEE e on e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_NAME;

SELECT c.CATEGORY_NAME, GROUP_CONCAT(p.PRODUCT_NAME SEPARATOR ', ') FROM CATEGORY c
JOIN PRODUCT p ON c.CATEGORY_ID = p.CATEGORY_ID
LEFT JOIN ORDER_POSITION op ON op.PRODUCT_ID = p.PRODUCT_ID
WHERE op.POSITION_ID IS NULL
GROUP BY c.CATEGORY_NAME;

SELECT IF(ORDER_STATUS IN (3,4,7,10), 'Zakończone', 'Inny') FROM `ORDER`;

SELECT p.PRODUCT_NAME,
    CASE
        WHEN i.AMOUNT > 30 THEN 'Duza ilosc'
        WHEN i.AMOUNT <= 30 THEN 'Srednia ilosc'
        WHEN i.AMOUNT < 10 THEN 'Mała ilosc'
        WHEN i.AMOUNT = 0 THEN 'Brak'
        ELSE 'wtf'
    END
FROM PRODUCT p
JOIN INVENTORY i ON i.PRODUCT_ID = p.PRODUCT_ID;

SELECT IFNULL(TAX_IDENTIFIER, 'Klient indywidualny') FROM CLIENT;

SELECT CITY, LEFT(POSTAL_CODE, 2) FROM CLIENT_ADDRESS;

SELECT CITY, GROUP_CONCAT(DISTINCT LEFT(POSTAL_CODE, 2)) FROM CLIENT_ADDRESS GROUP BY CITY;

SELECT SUBSTRING_INDEX(SUBSTR(STREET, LOCATE(' ', STREET) + 1), ' ', 1) FROM CLIENT_ADDRESS;

-- 8

SELECT c.FULL_NAME, ca.STREET, LENGTH(ca.STREET), LEFT(ca.STREET, 5) FROM CLIENT c
JOIN CLIENT_ADDRESS ca ON ca.CLIENT_ID = c.CLIENT_ID;

SELECT c.SHORT_NAME, at.ADDRESS_TYPE_NAME FROM CLIENT c
JOIN CLIENT_ADDRESS ca ON ca.CLIENT_ID = c.CLIENT_ID
LEFT JOIN ADDRESS_TYPE at ON at.ADDRESS_TYPE_ID = ca.ADDRESS_TYPE;

SELECT p.PRODUCT_NAME, c.CATEGORY_NAME, LEFT(p.PRODUCT_NAME, 3) FROM PRODUCT p
JOIN CATEGORY c ON c.CATEGORY_ID = p.CATEGORY_ID;

SELECT DISTINCT p.PRODUCT_NAME, p.DESCRIPTION FROM PRODUCT p
JOIN ORDER_POSITION op ON op.PRODUCT_ID = p.PRODUCT_ID;

SELECT c.FULL_NAME, o.ORDER_NUMBER, o.ORDER_DATE, DATEDIFF(CURDATE(), o.ORDER_DATE) FROM `ORDER` o
JOIN CLIENT c ON c.CLIENT_ID = o.CLIENT_ID;

SELECT o.ORDER_NUMBER, os.STATUS_NAME, o.ORDER_DATE, DATE_ADD(o.ORDER_DATE, INTERVAL 14 DAY)
FROM `ORDER` o JOIN ORDER_STATUS os ON os.STATUS_ID = o.ORDER_STATUS
WHERE os.STATUS_NAME NOT IN ('Zwrocone', 'Zamkniete');

SELECT e.FIRST_NAME, e.LAST_NAME, e.DATE_OF_EMPLOYMENT, DAYNAME(e.DATE_OF_EMPLOYMENT), d.DEPARTMENT_NAME FROM EMPLOYEE e
LEFT JOIN DEPARTMENT d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID;

SELECT c.FULL_NAME, COALESCE(DATEDIFF(MAX(o.ORDER_DATE), MIN(o.ORDER_DATE)), 0)
FROM CLIENT c
LEFT JOIN `ORDER` o ON o.CLIENT_ID = c.CLIENT_ID
GROUP BY c.FULL_NAME;

SELECT c.SHORT_NAME, GROUP_CONCAT(CONCAT_WS(' ', ca.POSTAL_CODE, ca.CITY, ca.STREET) SEPARATOR ', ')
FROM CLIENT c JOIN CLIENT_ADDRESS ca ON ca.CLIENT_ID = c.CLIENT_ID
GROUP BY c.SHORT_NAME;

SELECT CITY, GROUP_CONCAT(DISTINCT LEFT(POSTAL_CODE, 2) SEPARATOR ', ') FROM CLIENT_ADDRESS GROUP BY CITY;

SELECT CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME), d.DEPARTMENT_NAME, DATEDIFF(CURDATE(), e.DATE_OF_EMPLOYMENT), e.DATE_OF_EMPLOYMENT
FROM EMPLOYEE e
JOIN DEPARTMENT d ON d.DEPARTMENT_ID = e.DEPARTMENT_ID;

SELECT CONCAT(c.FULL_NAME, ' - ', c.SHORT_NAME), GROUP_CONCAT(RIGHT(o.ORDER_NUMBER, 3) SEPARATOR ', ') FROM CLIENT c
LEFT JOIN `ORDER` o ON o.CLIENT_ID = c.CLIENT_ID
GROUP BY c.FULL_NAME, c.SHORT_NAME;

SELECT CONCAT(LOWER(LEFT(FIRST_NAME, 3)), UPPER(RIGHT(LAST_NAME, 4)), CAST(LENGTH(CONCAT(FIRST_NAME, LAST_NAME)) AS CHAR))
FROM EMPLOYEE e;

-- 9

SELECT FIRST_NAME, LAST_NAME, pensja, RANK() OVER (ORDER BY pensja DESC) FROM EMPLOYEE;

SELECT FIRST_NAME, LAST_NAME, pensja,
RANK() OVER (ORDER BY pensja DESC),
SUM(pensja) OVER ()
FROM EMPLOYEE;

SELECT LAST_NAME, p.PRODUCT_NAME,
SUM(op.AMOUNT * op.SELL_PRICE) OVER (PARTITION BY e.EMPLOYEE_NAME) AS skum_wart_sprzedazy,
RANK() OVER (ORDER BY (op.AMOUNT * op.SELL_PRICE) DESC) AS rank_wart_sprzedazy_wzgl_wszystk_zamowien
FROM EMPLOYEE e
JOIN `ORDER` o ON o.EMPLOYEE_ID = e.EMPLOYEE_NAME
JOIN ORDER_POSITION op ON op.ORDER_ID = o.ORDER_ID
JOIN PRODUCT p ON p.PRODUCT_ID = op.PRODUCT_ID;

SELECT e.LAST_NAME, p.PRODUCT_NAME, op.SELL_PRICE,
COUNT(p.PRODUCT_ID) OVER (PARTITION BY p.PRODUCT_ID, o.ORDER_DATE) AS sprzed_tego_dnia,
SUM(op.AMOUNT * op.SELL_PRICE) OVER (PARTITION BY op.PRODUCT_ID, o.ORDER_DATE) AS suma_sprzedazy_dnia,
LAG(op.SELL_PRICE) OVER (PARTITION BY op.PRODUCT_ID ORDER BY o.ORDER_DATE, o.ORDER_ID) AS poprzednia_cena,
LEAD(op.SELL_PRICE) OVER (PARTITION BY op.PRODUCT_ID ORDER BY o.ORDER_DATE, o.ORDER_ID) AS nastepna_cena
FROM ORDER_POSITION op
JOIN `ORDER` o ON o.ORDER_ID = op.ORDER_ID
JOIN EMPLOYEE e ON e.EMPLOYEE_NAME = o.EMPLOYEE_ID
JOIN PRODUCT p ON p.PRODUCT_ID = op.PRODUCT_ID;

-- .5
SELECT p.PRODUCT_NAME, op.SELL_PRICE,
SUM(op.AMOUNT * op.SELL_PRICE) OVER (PARTITION BY YEAR(o.ORDER_DATE), MONTH(o.ORDER_DATE)) AS suma_calk_mc,
SUM(op.AMOUNT * op.SELL_PRICE) OVER
    (PARTITION BY YEAR(o.ORDER_DATE), MONTH(o.ORDER_DATE) ORDER BY o.ORDER_DATE, o.ORDER_ID) AS suma_rosnaca
FROM ORDER_POSITION op
JOIN PRODUCT p ON p.PRODUCT_ID = op.PRODUCT_ID
JOIN `ORDER` o ON o.ORDER_ID = op.ORDER_ID;

-- .5
SELECT p.PRODUCT_NAME, op.AMOUNT * op.SELL_PRICE AS cena, o.ORDER_DATE,
SUM(op.AMOUNT * op.SELL_PRICE) OVER (PARTITION BY YEAR(o.ORDER_DATE), MONTH(o.ORDER_DATE)) AS suma_mc,
SUM(op.AMOUNT * op.SELL_PRICE) OVER
    (PARTITION BY YEAR(o.ORDER_DATE), MONTH(o.ORDER_DATE) ORDER BY o.ORDER_DATE, op.PRODUCT_ID) AS suma_stepping
FROM ORDER_POSITION op
JOIN `ORDER` o ON o.ORDER_ID = op.ORDER_ID
JOIN PRODUCT p ON p.PRODUCT_ID = op.PRODUCT_ID;

-- .6
WITH s AS (SELECT c.CATEGORY_NAME AS CATEGORY_NAME,
                  SUM(CASE WHEN MONTH(o.ORDER_DATE) = 1 THEN op.AMOUNT * op.SELL_PRICE ELSE 0 END) AS suma_styczen,
                  SUM(CASE WHEN MONTH(o.ORDER_DATE) = 2 THEN op.AMOUNT * op.SELL_PRICE ELSE 0 END) AS suma_luty,
                  SUM(CASE WHEN MONTH(o.ORDER_DATE) = 3 THEN op.AMOUNT * op.SELL_PRICE ELSE 0 END) AS suma_marzec,
                  SUM(CASE WHEN MONTH(o.ORDER_DATE) = 4 THEN op.AMOUNT * op.SELL_PRICE ELSE 0 END) AS suma_kwiecien
           FROM CATEGORY c
                    JOIN PRODUCT p ON p.CATEGORY_ID = c.CATEGORY_ID
                    JOIN ORDER_POSITION op ON op.PRODUCT_ID = p.PRODUCT_ID
                    JOIN `ORDER` o ON o.ORDER_ID = op.ORDER_ID
           WHERE YEAR(o.ORDER_DATE) = 2025
           GROUP BY c.CATEGORY_NAME
)
SELECT s.CATEGORY_NAME,
       s.suma_styczen, s.suma_luty, s.suma_marzec, s.suma_kwiecien, ABS(s.suma_kwiecien - s.suma_styczen) AS rozn_kw_sty
FROM s;

-- .7
WITH s AS (SELECT c.CATEGORY_NAME,
                  p.PRODUCT_NAME,
                  op.AMOUNT * op.SELL_PRICE                                        AS cena,
                  MIN(op.AMOUNT * op.SELL_PRICE) OVER (PARTITION BY c.CATEGORY_ID) AS min_cena_w_kat,
                  MAX(op.AMOUNT * op.SELL_PRICE) OVER (PARTITION BY c.CATEGORY_ID) AS max_cena_w_kat
           FROM PRODUCT p
                    JOIN CATEGORY c ON c.CATEGORY_ID = p.CATEGORY_ID
                    JOIN ORDER_POSITION op ON op.PRODUCT_ID = p.PRODUCT_ID)
SELECT CATEGORY_NAME, PRODUCT_NAME, cena, min_cena_w_kat, max_cena_w_kat, max_cena_w_kat - min_cena_w_kat AS roznica FROM s;

-- .8
SELECT p.PRODUCT_NAME,
AVG(op.SELL_PRICE) OVER (PARTITION BY p.PRODUCT_ID ORDER BY o.ORDER_DATE, o.ORDER_ID ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING)
    AS step_avg
FROM PRODUCT p
JOIN ORDER_POSITION op ON op.PRODUCT_ID = p.PRODUCT_ID
JOIN `ORDER` o ON o.ORDER_ID = op.ORDER_ID;

-- .9
SELECT p.PRODUCT_NAME, c.CATEGORY_NAME,
RANK() OVER (PARTITION BY c.CATEGORY_ID ORDER BY p.PURCHASE_PRICE) AS ranking_cen_wewn_kat,
ROW_NUMBER() OVER (PARTITION BY c.CATEGORY_ID ORDER BY p.PURCHASE_PRICE) AS nr_w_kat_wg_ceny,
DENSE_RANK() OVER (PARTITION BY c.CATEGORY_ID ORDER BY p.PURCHASE_PRICE) AS ranking_gesty
FROM PRODUCT p
JOIN CATEGORY c ON c.CATEGORY_ID = p.CATEGORY_ID;

-- .10
SELECT e.LAST_NAME, p.PRODUCT_NAME, op.AMOUNT * op.SELL_PRICE AS wartosc_sprzedazy_pozycji, -- o.ORDER_DATE,
SUM(op.AMOUNT * op.SELL_PRICE) OVER (PARTITION BY e.EMPLOYEE_NAME ORDER BY o.ORDER_DATE) AS suma_sprzedazy_pracownika_wg_dat,
RANK() OVER (PARTITION BY e.EMPLOYEE_NAME ORDER BY op.AMOUNT * op.SELL_PRICE DESC) AS ranking_sprzedazy_dla_pracownika
FROM ORDER_POSITION op
JOIN `ORDER` o ON o.ORDER_ID = op.ORDER_ID
JOIN EMPLOYEE e ON e.EMPLOYEE_NAME = o.EMPLOYEE_ID
JOIN PRODUCT p ON p.PRODUCT_ID = op.PRODUCT_ID
ORDER BY e.LAST_NAME, o.ORDER_DATE;

-- .11
SELECT DISTINCT e.FIRST_NAME, e.LAST_NAME, jp.POSITION_NAME
FROM EMPLOYEE e
JOIN JOB_POSITION jp ON jp.JOB_POSITION_ID = e.JOB_POSITION_ID
LEFT JOIN `ORDER` o ON o.EMPLOYEE_ID = e.EMPLOYEE_NAME
WHERE o.ORDER_ID IS NOT NULL;

-- .4
SELECT e.LAST_NAME, p.PRODUCT_NAME, op.AMOUNT * op.SELL_PRICE AS cena_sprzedazy, o.ORDER_DATE,
COUNT(o.ORDER_ID) OVER (PARTITION BY p.PRODUCT_ID, o.ORDER_DATE) AS transakcje_w_dniu,
SUM(op.AMOUNT * op.SELL_PRICE) OVER (PARTITION BY p.PRODUCT_ID, o.ORDER_DATE) AS cena_w_dniu,
LAG(op.SELL_PRICE, 1) OVER (PARTITION BY p.PRODUCT_ID ORDER BY o.ORDER_DATE, o.ORDER_ID) AS poprzednia_cena,
LEAD(op.SELL_PRICE, 1) OVER (PARTITION BY p.PRODUCT_ID ORDER BY o.ORDER_DATE, o.ORDER_ID) AS nastepna_cena
FROM ORDER_POSITION op
JOIN `ORDER` o ON o.ORDER_ID = op.ORDER_ID
JOIN EMPLOYEE e ON e.EMPLOYEE_NAME = o.EMPLOYEE_ID
JOIN PRODUCT p ON p.PRODUCT_ID = op.PRODUCT_ID
ORDER BY p.PRODUCT_ID, o.ORDER_DATE;

