-- 1.1
CREATE TABLE infs_godlewskid.CLIENT SELECT * FROM company_2025.CLIENT;
CREATE TABLE infs_godlewskid.ORDER SELECT * FROM company_2025.ORDER;
CREATE TABLE infs_godlewskid.EMPLOYEE SELECT * FROM company_2025.EMPLOYEE;

-- 1.2
SELECT * FROM `ORDER`;

-- 1.3
SELECT * FROM `ORDER` WHERE ORDER_STATUS=5;

-- 1.4 
SELECT ORDER_ID, ORDER_STATUS FROM `ORDER` WHERE ORDER_ID IN (1,3,5);

-- 2.1
SELECT * FROM EMPLOYEE WHERE FIRST_NAME='Agnieszka' AND pensja=3900;

-- 2.2
SELECT * FROM EMPLOYEE WHERE pensja BETWEEN 5000 AND 7000;

-- 2.3
SELECT * FROM CLIENT WHERE SHORT_NAME LIKE '%ECO%' AND IS_COMPANY=1;

-- 3.1
SELECT * FROM `ORDER` WHERE MONTH(ORDER_DATE) IN (6,7);

-- 3.2
SELECT * FROM CLIENT WHERE TAX_IDENTIFIER IS NOT NULL ORDER BY SHORT_NAME ASC;

-- 3.3
SELECT * FROM EMPLOYEE ORDER BY BIRTH_DATE ASC LIMIT 5;

-- 4.1
SELECT DISTINCT FIRST_NAME FROM EMPLOYEE;

-- 4.2
SELECT CONCAT(FIRST_NAME, ' - ', LAST_NAME) FROM EMPLOYEE WHERE LAST_NAME LIKE 'Ko%';

-- 4.3
SELECT LAST_NAME, pensja FROM EMPLOYEE WHERE YEAR(DATE_OF_EMPLOYMENT) BETWEEN 2010 AND 2014;

-- 5.1
SELECT pensja, pensja - pensja*0.25 AS pensja_netto, pensja * 0.25 AS podatek FROM EMPLOYEE;

-- 5.2
SELECT * FROM CLIENT WHERE TAX_IDENTIFIER IS NULL;

-- 5.3
SELECT SHORT_NAME FROM CLIENT WHERE FULL_NAME LIKE 'K%' OR FULL_NAME LIKE '%ski' ORDER BY SHORT_NAME DESC;
