-- 1.1
SELECT C.FULL_NAME AS 'nazwa klienta', CA.STREET AS 'nazwa ulicy', LENGTH(CA.STREET) AS 'dlugosc ulicy', LEFT(CA.STREET, 5) AS 'pierwsze 5 liter ulicy' FROM CLIENT C JOIN CLIENT_ADDRESS CA ON C.CLIENT_ID = CA.CLIENT_ID;

-- 1.2
SELECT C.FULL_NAME AS 'pelna nazwa klienta', CA.STREET AS 'nazwa ulicy', LENGTH(CA.STREET) AS 'dlugosc ulicy', LEFT(CA.STREET, 5) AS 'pierwsze 5 liter Ulicy' FROM CLIENT C JOIN CLIENT_ADDRESS CA ON C.CLIENT_ID = CA.CLIENT_ID;

-- 1.3
SELECT P.PRODUCT_NAME AS 'produkt', CAT.CATEGORY_NAME AS 'kategoria', LEFT(P.PRODUCT_NAME, 3) AS 'pierwsz3 3 znaki produktu' FROM PRODUCT P JOIN CATEGORY CAT ON P.CATEGORY_ID = CAT.CATEGORY_ID;

-- 1.4
SELECT DISTINCT P.PRODUCT_NAME AS 'produkt', P.DESCRIPTION AS 'opis' FROM PRODUCT P JOIN ORDER_POSITION OP ON P.PRODUCT_ID = OP.PRODUCT_ID;

-- 2.1
SELECT C.FULL_NAME AS 'klient', O.ORDER_NUMBER AS 'nr zamowienia', O.ORDER_DATE AS 'data zamowienia', DATEDIFF(CURRENT_DATE(), O.ORDER_DATE) AS 'dni od daty zamowienia' FROM CLIENT C JOIN `ORDER` O ON C.CLIENT_ID = O.CLIENT_ID;

-- 2.2
SELECT O.ORDER_NUMBER AS 'nr zamowienia', O.ORDER_DATE AS 'data zamowienia', DATE_ADD(O.ORDER_DATE, INTERVAL 14 DAY) AS 'termin platnosci' FROM `ORDER` O JOIN ORDER_STATUS OS ON O.ORDER_STATUS = OS.STATUS_ID WHERE OS.STATUS_NAME NOT IN ('Zwrocone', 'Zamkniete');

-- 2.3 
SELECT E.FIRST_NAME AS 'imie', E.LAST_NAME AS 'nazwisko', E.DATE_OF_EMPLOYMENT AS 'data zatrudnienia', DAYNAME(E.DATE_OF_EMPLOYMENT) AS 'dzien tyg', D.DEPARTMENT_NAME AS 'nazwa dzialu' FROM EMPLOYEE E LEFT JOIN DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 2.4 
SELECT C.FULL_NAME AS 'klient', DATEDIFF(MAX(O.ORDER_DATE), MIN(O.ORDER_DATE)) AS 'dni miedzy zamowieniami' FROM CLIENT C LEFT JOIN `ORDER` O ON C.CLIENT_ID = O.CLIENT_ID GROUP BY C.CLIENT_ID, C.FULL_NAME;

-- 3.1
SELECT C.SHORT_NAME AS 'klient nazwa krotka', GROUP_CONCAT(CA.STREET SEPARATOR ', ') AS 'adresy' FROM CLIENT C JOIN CLIENT_ADDRESS CA ON C.CLIENT_ID = CA.CLIENT_ID GROUP BY C.CLIENT_ID, C.SHORT_NAME;

-- 3.2
SELECT CA.CITY AS 'miasto', GROUP_CONCAT(DISTINCT LEFT(CA.POSTAL_CODE, 2) SEPARATOR ', ') AS 'prefixy pocztowe' FROM CLIENT_ADDRESS CA GROUP BY CA.CITY;

-- 3.3
SELECT CONCAT(E.LAST_NAME, ' ', E.FIRST_NAME) AS 'nazwisko, imie', D.DEPARTMENT_NAME AS 'nazwa dzialu', DATEDIFF(CURRENT_DATE(), E.DATE_OF_EMPLOYMENT) AS 'dni od zatrudnienia' FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 3.4
SELECT CONCAT(C.FULL_NAME, ' - ', C.SHORT_NAME) AS 'pelna - krotka nazwa klienta', GROUP_CONCAT(RIGHT(O.ORDER_NUMBER, 3) ORDER BY O.ORDER_DATE SEPARATOR ', ') AS 'trzy ostatnie cyfry nr zamowien' FROM CLIENT C LEFT JOIN `ORDER` O ON C.CLIENT_ID = O.CLIENT_ID GROUP BY C.CLIENT_ID, C.FULL_NAME, C.SHORT_NAME;

-- 3.5
SELECT E.FIRST_NAME AS 'imie', E.LAST_NAME AS 'nazwisko', CONCAT(LOWER(LEFT(E.FIRST_NAME, 3)), UPPER(RIGHT(E.LAST_NAME, 4)), LENGTH(E.FIRST_NAME)) AS 'haslo' FROM EMPLOYEE E;